//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 基于云的Web管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminExecuteInfo
    {
        public long Id { get; set; }
        public string AdminNum { get; set; }
        public string AdminName { get; set; }
        public string ExecuteDescription { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public Nullable<byte> DelFlag { get; set; }
        public string Remark { get; set; }
    }
}
