//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 基于云的Web管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string UserPwd { get; set; }
        public string NickName { get; set; }
        public string TrueName { get; set; }
        public string Gender { get; set; }
        public string DeviceId { get; set; }
        public string State { get; set; }
        public string LastIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public Nullable<byte> DelFlag { get; set; }
        public string Remark { get; set; }
    }
}
