//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 基于云的Web管理系统.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebManagementDBEntities : DbContext
    {
        public WebManagementDBEntities()
            : base("name=WebManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminExecuteInfo> AdminExecuteInfo { get; set; }
        public DbSet<AdminInfo> AdminInfo { get; set; }
        public DbSet<AnswerInfo> AnswerInfo { get; set; }
        public DbSet<ForumInfo> ForumInfo { get; set; }
        public DbSet<ForumType> ForumType { get; set; }
        public DbSet<HealthInfo> HealthInfo { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
